"""add_user_invitation_tokens

Revision ID: 34afb76a4047
Revises: 4b7e96ee5ce9
Create Date: 2026-08-29 00:11:15.165094

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "34afb76a4047"
down_revision: str | None = "4b7e96ee5ce9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_invitation_tokens",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Globally unique primary key identifier (UUIDv4)",
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_user_invitation_tokens_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_invitation_tokens")),
    )
    op.create_index(
        "ix_user_invitation_tokens_token_hash",
        "user_invitation_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_user_invitation_tokens_user_id", "user_invitation_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_invitation_tokens_user_id", table_name="user_invitation_tokens")
    op.drop_index("ix_user_invitation_tokens_token_hash", table_name="user_invitation_tokens")
    op.drop_table("user_invitation_tokens")
    # ### end Alembic commands ###
