"""Add BatchScoreJob

Revision ID: d336f5d8940e
Revises: 'phase16_rls_001'
Create Date: 2026-08-13 11:29:47.659295

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d336f5d8940e"
down_revision: str | None = "phase16_rls_001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_score_jobs",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="Globally unique primary key identifier (UUIDv4)",
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("queued_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("completed_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "completed_candidate_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "failed_candidate_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp when the record was last updated",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'failed')",
            name=op.f("ck_batch_score_jobs_ck_batch_score_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_batch_score_jobs_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_batch_score_jobs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batch_score_jobs")),
    )
    op.create_index(
        op.f("ix_batch_score_jobs_job_id"), "batch_score_jobs", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_batch_score_jobs_tenant_id"), "batch_score_jobs", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_batch_score_jobs_tenant_id"), table_name="batch_score_jobs")
    op.drop_index(op.f("ix_batch_score_jobs_job_id"), table_name="batch_score_jobs")
    op.drop_table("batch_score_jobs")
    # ### end Alembic commands ###
